"""Compatibility facade for objective_grader.py old-API exports.

THIS IS THE ONLY app/ MODULE ALLOWED TO IMPORT legacy.
Do NOT add business logic, grading, or report generation here.
"""

from legacy import objective_grader_legacy as _legacy

COMPAT_EXPORTS = (
    "AnswerKey",
    "BankQuestion",
    "CHOICE_OPTIONS",
    "Counter",
    "Dict",
    "EPSILON",
    "ExamMeta",
    "FIELD_ALIASES",
    "FrozenSet",
    "Iterable",
    "KnowledgeProfile",
    "List",
    "OPTION_RE",
    "Optional",
    "Path",
    "QUESTION_RE",
    "QUESTION_STATUSES",
    "QuestionResult",
    "QuestionSpec",
    "Set",
    "StudentResult",
    "Submission",
    "TRUTHY",
    "Tuple",
    "advanced_dashboard_css",
    "allowed_options",
    "archive_reports",
    "argparse",
    "bar",
    "basic_stats",
    "build_abnormal_items",
    "build_class_report",
    "build_correct_question_ids",
    "build_knowledge_profiles",
    "build_parser",
    "build_question_accuracy_items",
    "build_score_distribution",
    "build_target_difficulties",
    "build_teaching_suggestions",
    "build_validation_report",
    "build_weak_items",
    "build_weak_tags",
    "competition_ranks",
    "create_sample_files",
    "csv",
    "dataclasses",
    "date",
    "datetime",
    "defaultdict",
    "difficulty_rank",
    "escape",
    "excel_column_name",
    "first_present",
    "format_answer",
    "format_expected_answer",
    "get_rate_class",
    "grade_all",
    "grade_submission",
    "html_escape",
    "is_choice_answer",
    "is_choice_like_answer",
    "item_stats",
    "json",
    "load_answer_key",
    "load_question_bank",
    "load_submissions",
    "main",
    "main_wrong_answer",
    "mastery_level",
    "matches_text_answer",
    "normalize_answer",
    "normalize_text_answer",
    "numeric_value",
    "parse_bool",
    "parse_difficulty",
    "parse_optional_float",
    "parse_question_number",
    "parse_status",
    "pct",
    "percent",
    "print_console_report",
    "re",
    "read_csv",
    "read_csv_for_workbook",
    "recommend_practice",
    "render_abnormal_table",
    "render_horizontal_bar_chart",
    "render_metric_cards",
    "render_option_distribution",
    "render_suggestion_cards",
    "render_table",
    "render_vertical_bar_chart",
    "render_wrong_top",
    "report_css",
    "report_link",
    "safe_slug",
    "score_answer",
    "score_answer_detail",
    "score_bands",
    "shutil",
    "simple_score_rows",
    "split_aliases",
    "split_tags",
    "statistics",
    "student_status_map",
    "sys",
    "worksheet_xml",
    "write_advanced_dashboard",
    "write_class_report",
    "write_detail",
    "write_dicts",
    "write_dicts_with_fields",
    "write_item_analysis",
    "write_knowledge_profiles",
    "write_practice_recommendations",
    "write_report_index",
    "write_simple_report",
    "write_simple_score_workbook",
    "write_student_report",
    "write_summary",
    "write_validation_report",
    "write_workbook",
    "write_xlsx",
    "xml_attr",
    "zipfile",
)


def export_compat_symbols() -> dict:
    """Return {name: obj} for all COMPAT_EXPORTS."""
    return {name: getattr(_legacy, name) for name in COMPAT_EXPORTS}


# Expose all symbols at module level so that:
#    from app.compat.objective_grader_compat import build_validation_report
# works just like the old objective_grader.py did.
globals().update(export_compat_symbols())
