from enum import Enum


class CaptureSourceType(str, Enum):
    MANUAL_UPLOAD = "MANUAL_UPLOAD"
    WATCHED_FOLDER = "WATCHED_FOLDER"
    BROWSER_CAMERA = "BROWSER_CAMERA"
    SYSTEM_CAMERA_PROBE_ONLY = "SYSTEM_CAMERA_PROBE_ONLY"
    MOBILE_WEB_UPLOAD_PLACEHOLDER = "MOBILE_WEB_UPLOAD_PLACEHOLDER"
    MOBILE_WEB_USB_CAMERA = "MOBILE_WEB_USB_CAMERA"
