"""Error code taxonomy for the Student Recognition Engine.

All ``blocking_errors`` entries and all ``review_items.reason_code`` values MUST
use members of :class:`ErrorCode`. Free-form natural-language strings are
forbidden by the constitution (§1 B6 / §10 / §18). This module is the single
source of truth for error codes.

Each member has a *stable string value* equal to its name so that serialized
artifacts (JSON / events) remain stable across refactors.
"""

from enum import Enum


class ErrorCode(str, Enum):
    """Stable, enumerable error / reason codes.

    The string value of every member equals its Python name (e.g.
    ``ErrorCode.IMG_BLUR_TOO_HIGH == "IMG_BLUR_TOO_HIGH"``). This guarantees
    round-trippable serialization and makes free-form strings unnecessary.
    """

    # ---- Image ----
    IMG_BLUR_TOO_HIGH = "IMG_BLUR_TOO_HIGH"
    IMG_TOO_DARK = "IMG_TOO_DARK"
    IMG_TOO_BRIGHT = "IMG_TOO_BRIGHT"
    IMG_LOW_CONTRAST = "IMG_LOW_CONTRAST"
    IMG_SHADOW_TOO_STRONG = "IMG_SHADOW_TOO_STRONG"
    IMG_TOO_SMALL = "IMG_TOO_SMALL"
    IMG_UNSUPPORTED_FORMAT = "IMG_UNSUPPORTED_FORMAT"
    IMG_UPLOAD_CORRUPTED = "IMG_UPLOAD_CORRUPTED"

    # ---- Page ----
    PAGE_NOT_FOUND = "PAGE_NOT_FOUND"
    PAGE_QUAD_INVALID = "PAGE_QUAD_INVALID"
    PAGE_COVERAGE_TOO_SMALL = "PAGE_COVERAGE_TOO_SMALL"
    PAGE_ASPECT_RATIO_INVALID = "PAGE_ASPECT_RATIO_INVALID"
    PAGE_PERSPECTIVE_TOO_EXTREME = "PAGE_PERSPECTIVE_TOO_EXTREME"
    PAGE_NORMALIZATION_FAILED = "PAGE_NORMALIZATION_FAILED"

    # ---- Template ----
    TEMPLATE_MISSING = "TEMPLATE_MISSING"
    TEMPLATE_VERSION_MISSING = "TEMPLATE_VERSION_MISSING"
    TEMPLATE_VERSION_MISMATCH = "TEMPLATE_VERSION_MISMATCH"
    TEMPLATE_PAGE_MISSING = "TEMPLATE_PAGE_MISSING"
    TEMPLATE_ROI_OUT_OF_BOUNDS = "TEMPLATE_ROI_OUT_OF_BOUNDS"
    TEMPLATE_OPTION_CELL_MISSING = "TEMPLATE_OPTION_CELL_MISSING"
    TEMPLATE_IDENTITY_ROI_MISSING = "TEMPLATE_IDENTITY_ROI_MISSING"

    # ---- ROI ----
    ROI_OUT_OF_BOUNDS = "ROI_OUT_OF_BOUNDS"
    ROI_EMPTY_CROP = "ROI_EMPTY_CROP"
    ROI_TOO_SMALL = "ROI_TOO_SMALL"
    ROI_CROP_FAILED = "ROI_CROP_FAILED"

    # ---- OMR ----
    OMR_WEAK_MARK = "OMR_WEAK_MARK"
    OMR_EMPTY_MARK = "OMR_EMPTY_MARK"
    OMR_MULTI_MARK_SINGLE_CHOICE = "OMR_MULTI_MARK_SINGLE_CHOICE"
    OMR_AMBIGUOUS_MULTI_CHOICE = "OMR_AMBIGUOUS_MULTI_CHOICE"
    OMR_BORDER_NOISE_HIGH = "OMR_BORDER_NOISE_HIGH"
    OMR_ERASURE_DETECTED = "OMR_ERASURE_DETECTED"
    OMR_LOW_CONFIDENCE = "OMR_LOW_CONFIDENCE"
    OMR_OPTION_CELL_MISSING = "OMR_OPTION_CELL_MISSING"

    # ---- Identity ----
    IDENTITY_MISSING = "IDENTITY_MISSING"
    IDENTITY_LOW_CONFIDENCE = "IDENTITY_LOW_CONFIDENCE"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
    IDENTITY_DUPLICATE = "IDENTITY_DUPLICATE"
    IDENTITY_ROSTER_NOT_FOUND = "IDENTITY_ROSTER_NOT_FOUND"
    IDENTITY_NAME_ONLY = "IDENTITY_NAME_ONLY"
    IDENTITY_STUDENT_ID_ONLY_UNMATCHED = "IDENTITY_STUDENT_ID_ONLY_UNMATCHED"

    # ---- Draft / Review ----
    DRAFT_HAS_BLOCKING_ERRORS = "DRAFT_HAS_BLOCKING_ERRORS"
    DRAFT_HAS_UNRESOLVED_REVIEW = "DRAFT_HAS_UNRESOLVED_REVIEW"
    REVIEW_ITEM_UNRESOLVED = "REVIEW_ITEM_UNRESOLVED"
    TEACHER_CONFIRMATION_REQUIRED = "TEACHER_CONFIRMATION_REQUIRED"
    TEACHER_OVERRIDE_REQUIRES_NOTE = "TEACHER_OVERRIDE_REQUIRES_NOTE"

    # ---- Bundle ----
    BUNDLE_MISSING_PAGE = "BUNDLE_MISSING_PAGE"
    BUNDLE_DUPLICATE_PAGE = "BUNDLE_DUPLICATE_PAGE"
    BUNDLE_IDENTITY_CONFLICT = "BUNDLE_IDENTITY_CONFLICT"
    BUNDLE_TEMPLATE_VERSION_MISMATCH = "BUNDLE_TEMPLATE_VERSION_MISMATCH"
    BUNDLE_PAGE_ORDER_UNKNOWN = "BUNDLE_PAGE_ORDER_UNKNOWN"

    # ---- Grading Gate ----
    GRADING_DRAFT_NOT_CONFIRMED = "GRADING_DRAFT_NOT_CONFIRMED"
    GRADING_IDENTITY_NOT_CONFIRMED = "GRADING_IDENTITY_NOT_CONFIRMED"
    GRADING_BLOCKING_ERRORS_EXIST = "GRADING_BLOCKING_ERRORS_EXIST"
    GRADING_UNRESOLVED_REVIEW_ITEMS = "GRADING_UNRESOLVED_REVIEW_ITEMS"
    GRADING_EXAM_HAS_DUPLICATE_STUDENT = "GRADING_EXAM_HAS_DUPLICATE_STUDENT"
    GRADING_EXAM_HAS_MISSING_STUDENTS = "GRADING_EXAM_HAS_MISSING_STUDENTS"
    GRADING_ANSWER_KEY_NOT_ACCEPTED = "GRADING_ANSWER_KEY_NOT_ACCEPTED"

    # ---- Internal fallback ----
    INTERNAL_UNKNOWN_ERROR = "INTERNAL_UNKNOWN_ERROR"

    def __str__(self) -> str:  # pragma: no cover - convenience
        return self.value


# Canonical category names (kept as plain strings to avoid import cycles).
CATEGORY_IMAGE = "image"
CATEGORY_PAGE = "page"
CATEGORY_TEMPLATE = "template"
CATEGORY_ROI = "roi"
CATEGORY_OMR = "omr"
CATEGORY_IDENTITY = "identity"
CATEGORY_DRAFT_REVIEW = "draft_review"
CATEGORY_BUNDLE = "bundle"
CATEGORY_GRADING_GATE = "grading_gate"
CATEGORY_INTERNAL = "internal"
