from enum import Enum


class TeacherAction(str, Enum):
    BIND_IDENTITY = "BIND_IDENTITY"
    CREATE_TEMPORARY_STUDENT = "CREATE_TEMPORARY_STUDENT"
    MANUAL_SCORE = "MANUAL_SCORE"
    MARK_WRONG = "MARK_WRONG"
    MARK_BLANK = "MARK_BLANK"
    WAIVE = "WAIVE"
    EXCLUDE = "EXCLUDE"
    EXCLUDE_CAPTURE = "EXCLUDE_CAPTURE"
